version: '2'

services:
     
    stream_icecast:
        image: silentprotest/icecast-arm
        build: icecast
        networks:
            - www
            - stream
        volumes:
            - ./icecast/icecast.xml:/etc/icecast2/icecast.xml:ro
        ports:
            - 1337:8000
        restart: always

    stream_liquidsoap:
        image: silentprotest/liquidsoap-arm
        build: liquidsoap/
        networks:
            - stream
        volumes:
             - ./media/:/media/radio:ro
        depends_on:
            - stream_icecast
        restart: always

    video_server:
        image: silentprotest/hublin-arm
        build: video/
        networks:
            - www
            - video_db
        environment:
            - HUBLIN_REDIS_HOST=video_redis
        ports:
            - 82:8080
        depends_on:
            - video_redis
            - video_mongo
        restart: always

    video_mongo:
        image: silentprotest/mongo-arm
        build: mongo/
        networks:
            - video_db
        volumes:
            - video_mongo_data:/data/db
            - video_mongo_config:/data/configdb
        restart: always

    video_redis:
        image: armhf/redis
        networks:
            - video_db
        volumes:
            - video_redis_data:/data
        restart: always

    www:
        image: armhfbuild/nginx
        networks:
            - www
        volumes:
            - ./www/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./www/conf.d/:/etc/nginx/conf.d/:ro
            - ./www/party/html:/usr/share/nginx/html:ro
            - ./www/fullchain.pem:/ssl.crt:ro
            - ./www/privkey.pem:/ssl.key:ro
            - www_cache:/var/cache/nginx
        ports:
            - 80:80
            - 443:443
        restart: always


networks:
    video_db:
    stream:
    www:

volumes:
    video_mongo_data: {}
    video_mongo_config: {}
    video_redis_data: {}
    www_config: {}
    www_cache: {}

